# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
 adapter: mysql2
 encoding: utf8
 database: sakura_development_develop06
 pool: 5
 username: root
 password:
 socket: /tmp/mysql.sock
 connect_timeout: 10
 host: 127.0.0.1
 port: 3307

development:
  <<: *default
  database: sakura_development_develop06

test:
  <<: *default
  database: project_test

production:
  <<: *default
  database: project_production
  username: username
  password: passowrk
